// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Event struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Location  string `json:"location"`
	StartDate string `json:"startDate"`
	EndDate   string `json:"endDate"`
	URL       string `json:"url"`
}

type EventPlayer struct {
	Name        string  `json:"name"`
	Country     string  `json:"country"`
	Wins        *int    `json:"wins,omitempty"`
	Losses      *int    `json:"losses,omitempty"`
	Ties        *int    `json:"ties,omitempty"`
	Points      *int    `json:"points,omitempty"`
	DecklistURL *string `json:"decklistURL,omitempty"`
	Standing    *int    `json:"standing,omitempty"`
}

type EventRounds struct {
	Juniors *int `json:"juniors,omitempty"`
	Seniors *int `json:"seniors,omitempty"`
	Masters *int `json:"masters,omitempty"`
}

type Match struct {
	Player1 *EventPlayer `json:"player1"`
	Player2 *EventPlayer `json:"player2"`
	Table   int          `json:"table"`
	Winner  *EventPlayer `json:"winner"`
}

type Player struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Country   string `json:"country"`
}

type Query struct {
}
